//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Setting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Setting() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bimacad.Sys.Resources.Setting", typeof(Setting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлено.
        /// </summary>
        public static string AddedQnt {
            get {
                return ResourceManager.GetString("AddedQnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a new unload action in IFC format (.ifc).
        /// </summary>
        public static string AddIFCJob {
            get {
                return ResourceManager.GetString("AddIFCJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a new unload action in  Navisworks (.nwc).
        /// </summary>
        public static string AddNavisJob {
            get {
                return ResourceManager.GetString("AddNavisJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a new unload action in Revit format (.rvt).
        /// </summary>
        public static string AddRevitJob {
            get {
                return ResourceManager.GetString("AddRevitJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Именования моделей.
        /// </summary>
        public static string AffixesLinks {
            get {
                return ResourceManager.GetString("AffixesLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прикрепить ссылки.
        /// </summary>
        public static string AffixLinks {
            get {
                return ResourceManager.GetString("AffixLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на выполняется.
        /// </summary>
        public static string AtWork {
            get {
                return ResourceManager.GetString("AtWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аудит.
        /// </summary>
        public static string Audit {
            get {
                return ResourceManager.GetString("Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт основных величин.
        /// </summary>
        public static string BasicValues {
            get {
                return ResourceManager.GetString("BasicValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начало.
        /// </summary>
        public static string BeginTime {
            get {
                return ResourceManager.GetString("BeginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать вид.
        /// </summary>
        public static string ChooseView {
            get {
                return ResourceManager.GetString("ChooseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станция.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть все рабочие наборы.
        /// </summary>
        public static string CloseWorksets {
            get {
                return ResourceManager.GetString("CloseWorksets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профиль.
        /// </summary>
        public static string CollectionName {
            get {
                return ResourceManager.GetString("CollectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профили.
        /// </summary>
        public static string CollectionsCaption {
            get {
                return ResourceManager.GetString("CollectionsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершено.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конвертировать идентификаторы элементов.
        /// </summary>
        public static string ConvertIdentif {
            get {
                return ResourceManager.GetString("ConvertIdentif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только текущий вид.
        /// </summary>
        public static string CurrentView {
            get {
                return ResourceManager.GetString("CurrentView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя вида.
        /// </summary>
        public static string CurrentViewName {
            get {
                return ResourceManager.GetString("CurrentViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По умолчанию.
        /// </summary>
        public static string DefaultClient {
            get {
                return ResourceManager.GetString("DefaultClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущая.
        /// </summary>
        public static string DefaultVersion {
            get {
                return ResourceManager.GetString("DefaultVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть с отсоединением.
        /// </summary>
        public static string Detach {
            get {
                return ResourceManager.GetString("Detach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разделить файлы на уровни.
        /// </summary>
        public static string DevideFiles {
            get {
                return ResourceManager.GetString("DevideFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Директория (полный путь).
        /// </summary>
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файловые хранилища.
        /// </summary>
        public static string DirectoryCaptions {
            get {
                return ResourceManager.GetString("DirectoryCaptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разделить стены и колонны на этаже.
        /// </summary>
        public static string DivideWalls {
            get {
                return ResourceManager.GetString("DivideWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть без отсоединения.
        /// </summary>
        public static string DoNotDetach {
            get {
                return ResourceManager.GetString("DoNotDetach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Элементы.
        /// </summary>
        public static string Elements {
            get {
                return ResourceManager.GetString("Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Окончание.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исключения (через &quot;,&quot; или &quot;;&quot;).
        /// </summary>
        public static string ExceptionsWorksets {
            get {
                return ResourceManager.GetString("ExceptionsWorksets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исключения (через &quot;,&quot; или &quot;;&quot;).
        /// </summary>
        public static string ExceptionViews {
            get {
                return ResourceManager.GetString("ExceptionViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспортировать геометрию помещения.
        /// </summary>
        public static string ExportGeometryRoom {
            get {
                return ResourceManager.GetString("ExportGeometryRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модели Revit.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Первый уровень.
        /// </summary>
        public static string First_Level {
            get {
                return ResourceManager.GetString("First Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пт.
        /// </summary>
        public static string Fr {
            get {
                return ResourceManager.GetString("Fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип файлов.
        /// </summary>
        public static string IFCFileType {
            get {
                return ResourceManager.GetString("IFCFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить границы пространств.
        /// </summary>
        public static string IFCIncludeBoundaty {
            get {
                return ResourceManager.GetString("IFCIncludeBoundaty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутренние.
        /// </summary>
        public static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действия.
        /// </summary>
        public static string JobCollection {
            get {
                return ResourceManager.GetString("JobCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действия.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на последние 3 мес..
        /// </summary>
        public static string Last3MonthsCapt {
            get {
                return ResourceManager.GetString("Last3MonthsCapt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использования (3 мес).
        /// </summary>
        public static string Last3MonthsQnt {
            get {
                return ResourceManager.GetString("Last3MonthsQnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дней пользования (3 мес).
        /// </summary>
        public static string Last3MonthsUniqQnt {
            get {
                return ResourceManager.GetString("Last3MonthsUniqQnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последняя активность.
        /// </summary>
        public static string LastActivites {
            get {
                return ResourceManager.GetString("LastActivites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последний запуск.
        /// </summary>
        public static string LastStart {
            get {
                return ResourceManager.GetString("LastStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновлено.
        /// </summary>
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общее количество рабочих мест.
        /// </summary>
        public static string LicenseQnt {
            get {
                return ResourceManager.GetString("LicenseQnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общее количество пользователей.
        /// </summary>
        public static string LicenseUsedQnt {
            get {
                return ResourceManager.GetString("LicenseUsedQnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время постановки в очередь.
        /// </summary>
        public static string LogTime {
            get {
                return ResourceManager.GetString("LogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пн.
        /// </summary>
        public static string Mo {
            get {
                return ResourceManager.GetString("Mo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модели Revit.
        /// </summary>
        public static string Models {
            get {
                return ResourceManager.GetString("Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конвертировать параметры элементов.
        /// </summary>
        public static string NavisConvertElementsProperty {
            get {
                return ResourceManager.GetString("NavisConvertElementsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Координаты.
        /// </summary>
        public static string NavisCoordinate {
            get {
                return ResourceManager.GetString("NavisCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт вида.
        /// </summary>
        public static string NavisView {
            get {
                return ResourceManager.GetString("NavisView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Следующий запуск.
        /// </summary>
        public static string NextStart {
            get {
                return ResourceManager.GetString("NextStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не назначено.
        /// </summary>
        public static string NotAssigned {
            get {
                return ResourceManager.GetString("NotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на текущ..
        /// </summary>
        public static string NowCapt {
            get {
                return ResourceManager.GetString("NowCapt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры открытия.
        /// </summary>
        public static string OpenParams {
            get {
                return ResourceManager.GetString("OpenParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть все рабочие наборы.
        /// </summary>
        public static string OpenWorksets {
            get {
                return ResourceManager.GetString("OpenWorksets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на из.
        /// </summary>
        public static string OutOf {
            get {
                return ResourceManager.GetString("OutOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры экспорта.
        /// </summary>
        public static string ParamsExport {
            get {
                return ResourceManager.GetString("ParamsExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры и расписание.
        /// </summary>
        public static string ParamsSetting {
            get {
                return ResourceManager.GetString("ParamsSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь для экспорта.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить неиспользуемые.
        /// </summary>
        public static string Purge {
            get {
                return ResourceManager.GetString("Purge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалено.
        /// </summary>
        public static string RemovedQnt {
            get {
                return ResourceManager.GetString("RemovedQnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результат.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя Revit Server.
        /// </summary>
        public static string RevitServerName {
            get {
                return ResourceManager.GetString("RevitServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сб.
        /// </summary>
        public static string Sa {
            get {
                return ResourceManager.GetString("Sa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расписание.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Второй уровень.
        /// </summary>
        public static string Second_Level {
            get {
                return ResourceManager.GetString("Second Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Серверы Revit.
        /// </summary>
        public static string ServerCaption {
            get {
                return ResourceManager.GetString("ServerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внешние.
        /// </summary>
        public static string Shared {
            get {
                return ResourceManager.GetString("Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вс.
        /// </summary>
        public static string Su {
            get {
                return ResourceManager.GetString("Su", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успешно.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чт.
        /// </summary>
        public static string Th {
            get {
                return ResourceManager.GetString("Th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверять и находить отсутствующие материалы.
        /// </summary>
        public static string TransformConstructionElements {
            get {
                return ResourceManager.GetString("TransformConstructionElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Преобразовать свойства элементов.
        /// </summary>
        public static string TransformElementsProperty {
            get {
                return ResourceManager.GetString("TransformElementsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Преобразовать связанные файлы.
        /// </summary>
        public static string TransformLinkedFiles {
            get {
                return ResourceManager.GetString("TransformLinkedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Преобразовать помещения как атрибут.
        /// </summary>
        public static string TransformRoom {
            get {
                return ResourceManager.GetString("TransformRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Преобразовать URL адреса.
        /// </summary>
        public static string TransformURL {
            get {
                return ResourceManager.GetString("TransformURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить все ссылки.
        /// </summary>
        public static string TruncateLinks {
            get {
                return ResourceManager.GetString("TruncateLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить все виды.
        /// </summary>
        public static string TruncateView {
            get {
                return ResourceManager.GetString("TruncateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вт.
        /// </summary>
        public static string Tu {
            get {
                return ResourceManager.GetString("Tu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия Revit.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование вида.
        /// </summary>
        public static string ViewName {
            get {
                return ResourceManager.GetString("ViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ср.
        /// </summary>
        public static string We {
            get {
                return ResourceManager.GetString("We", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дни недели.
        /// </summary>
        public static string WeekDays {
            get {
                return ResourceManager.GetString("WeekDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Весь проект.
        /// </summary>
        public static string WholeProject {
            get {
                return ResourceManager.GetString("WholeProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рабочие наборы.
        /// </summary>
        public static string Worksets {
            get {
                return ResourceManager.GetString("Worksets", resourceCulture);
            }
        }
    }
}
